language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: 
    secure: '$NPM_TOKEN'
  on:
    tags: true
    repo: mlomboglia/yt-list
  skip_cleanup: 'true'
