language: node_js
node_js:
- node
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key:
    secure: '$NPM_TOKEN'
  on:
    tags: true
    repo: mlomboglia/yt-list
  skip_cleanup: 'true'
branches:
  only:
    - master
    - /^v[0-9]+.*$/



