language: node_js
node_js:
- node
deploy:
  provider: npm
  email: hello@marcoslombog.com
  api_key:
    secure: "$NPM_TOKEN"
  on:
    tags: true
    repo: mlomboglia/yt-list
  skip_cleanup: 'true'


